### PR TITLE
Two Fixes: Components Style, LiveScript

### PR DESCRIPTION
**Pull request by michael-brade**
Hi Nate,

see the two commits for details. I thought components were supposed to load their styles, but they don't. This is now fixed. Also, I am writing my code in LiveScript, however, components didn't work without this patch. 

Cheers, Michael

### CODE REVIEW

**Comment by enjalot** [comment]
is there a reason so many of the commits in master are included in your PR? makes it very difficult to evaluate your changes.

**Comment by michael-brade** [comment]
No, I have no idea why this happened.  All I keep doing is

    git pull upstream master
    git pull
    git push

But you can click on my two commits at the top to see the changes, they are very simple, just adding a few lines of code. It shouldn't have affected all the other commits.

**Comment by michael-brade** [comment]
Ok, finally fixed it with --force. The last `git pull` messed it up for some reason.

**Comment by zag2art** [comment]
"Separate style files" for components doesn't fit for stylus files. We've discussed the issue somewhere.

**Comment by zag2art** [comment]
I've found. It's here - https://github.com/derbyjs/derby/pull/477

**Comment by michael-brade** [comment]
I see, I missed that plugin (I am using sass, btw). But if you cannot merge it, shouldn't the docs be updated then? See http://derbyjs.com/docs/derby-0.6/components/structure, it mentions `Controller.prototype.style`, which won't work.

**Comment by michael-brade** [comment]
I close this pr since it used the master branch, which was a bad idea, and there is no way to change the branch.

**Pull request closed without merging**
